# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET_first_build_and_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-direcory: ./StringManipulationApp

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./StringManipulationApp
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./StringManipulationApp
    - name: Test
      working-directory: ./BasicTests
      run: dotnet test --no-restore --no-build --verbosity normal
      
    - name: Set issue body
      run: echo "::set-env name=GITHUB_ISSUE_BODY::One or more test failed on main by ${{ github.actor }}'s commit.\n$(date +'%A, %B %d')"
    
    - name: Create an Issue
      if: always()
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/custom.md
            
