# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET_first_build_and_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-direcory: ./StringManipulationApp

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./StringManipulationApp
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./StringManipulationApp
    - name: Test
      working-directory: ./StringManipulationApp
      run: dotnet test --no-restore --no-build --verbosity normal
